[Icon Theme]
Name=Adwaita
Comment=Iconos de respaldo para R.E.A.C.T.O.R (IDK)
Hidden=true
Inherits=AdwaitaLegacy,hicolor
Directories=scalable/actions,scalable/status,scalable/devices,scalable/places,scalable/categories,scalable/mimetypes,scalable/legacy

[scalable/actions]
Size=16
Type=Scalable
Context=Actions

[scalable/status]
Size=16
Type=Scalable
Context=Status

[scalable/devices]
Size=16
Type=Scalable
Context=Devices

[scalable/places]
Size=16
Type=Scalable
Context=Places

[scalable/categories]
Size=16
Type=Scalable
Context=Categories

[scalable/mimetypes]
Size=16
Type=Scalable
Context=MimeTypes

[scalable/legacy]
Size=16
Type=Scalable
Context=Legacy
